---
title: "Elements of Data Science <br> SDS 322E"
author: "H. Sherry Zhang <br> Department of Statistics and Data Sciences <br> The University of Texas at Austin <br>  <br> week 01 lecture 01 Fall 2025"
format: 
  revealjs:
    scrollable: true
    slide-number: true
    show-slide-number: all
    aspectratio: 169
    theme: serif
    preview-links: auto
    pdf-separate-fragments: true
---

# SDS 322E: Elements of Data Science

lecture, lab, instructor, Grad TA: UGCAs:

# Course schedule

# Weekly schedule

# Assessement

# Learning objectives

end goal: be comfortable to code in R to do some analysis and have enough breadth of knowledge to know where to look for things you need

# Why data science \[to fill\]

# What you will (not) expect

- picture of math equation


# Install R and RStudio

-   Git and GitHub - not required for the course, but nice to have an online profile of activities for portfolio and see more software details.
    -   Activity: install Git, register for GitHub

# R programming

- base R
- packages available on CRAN (or BioConductor): `install.packages()` - pkgs are generally safe!
- packages on GitHub: `remotes::install_github()`


# RStudio IDE (screenshot)

# Resources:

  - R for Data Science https://r4ds.hadley.nz/
  - **ggplot2: Elegant Graphics for Data Analysis (3e)** https://ggplot2-book.org/
  - [Stack Overflow](https://stackoverflow.com/questions/tagged/ggplot2?sort=frequent&pageSize=50) is a great source of answers to common ggplot2 questions. It is also
a great place to get help, once you have created a reproducible
example that illustrates your problem.

# Trick 101 to make you slightly more comfortable in R:

## Do you know that:

-   `Command + ,` pulls out the options panel, which you can:
    -   Pane Layout: rearrange panels. add multiple Source Panes for multiple scripts (for long screen),
    -   Appearance: add an editor theme
-   error msg you don’t understand: search on Google: use rstats

## Coding is never memorization! 

Ask anyone you know working with data or software to write down what they just code on a piece of paper: fail…

  - we use a lot of auto-complete, help, and reference!
  

## What I mean by this:

- if you can’t remember the details of a particular function or an argument, do `?dplyr::summarise` - go through the help page: 1) details of arguments, 2) examples
- package pkgdown site: go to https://github.com/tidyverse/ggplot2, click the link
    - the reference page has all the functions available in the package → click one to see the documentation
    - a Get started page for introductory materials
    - more vignettes under the Articles tab

## Quarto and Rmarkdown document

write your things in a R script for programming, but mostly you will interact with RMarkdown/ Quarto document 

  - Quarto: you can “write/ run code” in a “Word document”: open a template and render a pdf, 
  - also render into a html document 
  - do you know that: you can also write papers, books, making slides, writing CV, create website all with Quarto documents

# About me: Postdoc, research on visualization, data analysis,


# Data as the main object 

# pipe 


# Use of LLMs

 - make up functions, old functions...
