---
title: "Elements of Data Science <br> SDS 322E"
author: "H. Sherry Zhang <br> Department of Statistics and Data Sciences <br> The University of Texas at Austin <br>  <br> Fall 2025"
format: 
  revealjs:
    scrollable: true
    slide-number: true
    show-slide-number: all
    aspectratio: 169
    smaller: true
    theme: serif
    preview-links: auto
    pdf-separate-fragments: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center")
options(pillar.width = 70, pillar.print_max = 5, pillar.print_min = 5)
library(tidyverse)
library(nycflights13)
```

## Learning objective 

Apart from the `mutate()`, `filter()`, `group_by()`, `summarize()`, and `arrange()` we introduced last week, there are a few others you should know about:

- `pull()`: extract a single column as a vector
- `select()`: select variables by name or position
- `rename()`: rename variables
- `distinct()`: find unique values
- `between()`: filter by a range
- `if_else()`/ `ifelse()`: create a new variable based on a condition
- `case_when()`: create a new variable based on multiple conditions

We will practice these by examples:

<center>`usethis::create_from_github("SDS322E-2025FALL/03-01-dplyr2")`</center>


## If have extra time after finishing the hangout, you can try the following:

With the `mtcars` data:

1) Convert the `mpg` variable into `kpl` (1 mpg = 0.425144 km/l)
2) Only look at V-shaped engine *Hint: look at the documentation to see what this means*
3) Find the average `kpl` and `disp` for each number of cylinders
4) Arrange the result by `disp` in descending order 
